language: python

services:
  - docker

before_install:
- mv config/config.env.example config/config.env
- docker-compose build

script:
- docker-compose up -d

# jobs:
#   include:
#     - stage: test
#       language: python
#       python:
#         - '3.6.8'
#       sudo: enabled
#       services:
#         - redis-server
#       install:
#         - cd backend
#         - pip install -r requirements.txt   
#       before_script:
#         - python manage.py makemigrations
#         - python manage.py migrate
#       script:
#         - python manage.py test

    # - stage: test
    #   language: node_js
    #   node_js:
    #     - stable
    #   cache:
    #     directories:
    #       - node_modules
    #   env:
    #     global:
    #       - TRAVIS=true
    #   install:
    #     - npm install -g gulp
    #   script:
    #     - cd frontend
    #     - npm install && npm run start
  
