language: node_js|python
sudo: enabled
node_js:
  - stable

cache:
  directories:
    - node_modules
python:
  - "3.7"
env:
    global:
     - TRAVIS=true
install:
    - pip install -r requirements.txt 
before_script:
   - npm install -g gulp
script: 
    - python ./backend/manage.py test
    - cd frontend && npm install && npm run start
  