language: python
sudo: enabled
node_js:
  - stable
python:
  - "3.7"
cache:
  directories:
    - node_modules
env:
    global:
     - TRAVIS=true
install:
    - sudo pip install -r requirements.txt 
before_script:
   - npm install -g gulp
script: 
    - python ./backend/manage.py test
    - cd frontend && npm install && npm run start
  