jobs:
  include:
    - stage: test
      language: python
      python:
        - '3.7'
      sudo: enabled
      env:
          global:
           - TRAVIS=true
      install:
        - pip install -r requirements.txt   
      before_script:
        - cd backend
        - python manage.py makemigrations
        - python manage.py migrate
      script:
        - python manage.py test
    - stage: test
      language: node_js
      node_js:
        - stable
      cache:
        directories:
          - node_modules
      env:
        global:
          - TRAVIS=true
      install:
        - npm install -g gulp
      script:
        - cd frontend
        - npm install && npm run start
  
